
ssid=Vic_Pi_AP

interface=uap0
driver=nl80211
country_code=TW
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1

# 停用加密（不設密碼的關鍵）
auth_algs=1
wmm_enabled=1
 
# 移除或註解掉以下 WPA 相關設定
#wpa=2
#wpa_key_mgmt=WPA-PSK
#rsn_pairwise=CCMP
#wpa_passphrase=12320400
